<html>  
<head>         
<meta http-equiv="content-type" content="text/html;charset=utf8"> 
<style type="text/css">
.result{
	width: 800px;
}
.div_success{
	margin: 4px auto;
	border-top: solid 1px #E1E8F0;
	border-bottom: solid 1px #E1E8F0;
}
.div_failed{
	margin: 4px auto;
	border-bottom: solid 1px #E1E8F0;
}
.table_data{
	font-size: 11px;
	width: 100%;
	border: solid 1px #E1E8F0;
	border-collapse: collapse;
}
.table_data td {
	border-bottom: solid 1px #E1E8F0;
	border-right: solid 1px #E1E8F0;
	padding: 3px 5px 4px 10px;
}
.div_site{
	color: gray;
	font-size: 1.0em;
	margin: 5px auto;
}
.note{
	margin: 5px auto;
	font-size: 0.9em;
	color: gray;
}

</style>
</head>  
<body>           
<b>Dear ${RegisteredUser}</b>,		
<br>
<p>The staging files has been transferred to the collection - <b>${Collection}</b> with the following results:</p>
<div class="result">
	<div class="div_success">
		<p>${SuccessNum} of total ${TotalFiles} datasets are successful.</p>
	</div>
	<br>
	<div class="div_failed">
 		<p>${FailureNum} of total ${TotalFiles} datasets are failed.</p>
 		${ErrorReports}
 		<br>
 	</div>
</div>
<div class="div_site">${SiteName}</div>
<b>${AppName} - Stage Transfer Service</b> 
<div class="note"><b>NOTE:</b> Please do not reply to this message, which was automatically generated by the system. Mail sent to this address cannot be answered.</div>
</body>  
</html>  