<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>net.javaguides.springmvc</groupId>
    <artifactId>au.edu.monash.merc.capture</artifactId>
    <packaging>war</packaging>
    <version>v3.0</version>
    <name>Eddy App</name>
    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <failOnMissingWebXml>false</failOnMissingWebXml>
        <spring.version>4.3.30.RELEASE</spring.version>
        <hibernate.version>4.3.11.Final</hibernate.version>
        <hibernate-commons-annotations.version>4.0.5.Final</hibernate-commons-annotations.version>
        <hibernate.validator.version>4.3.2.Final</hibernate.validator.version>
        <c3p0.version>0.9.5.5</c3p0.version>
        <servlets.version>3.1.0</servlets.version>
        <freemarker.version>2.3.34</freemarker.version>
        <postgresql.version>42.7.4</postgresql.version>
        <reload4j.version>1.2.26</reload4j.version>
        <struts2.version>2.3.37</struts2.version>
        <struts2-jquery-plugin.version>3.5.1</struts2-jquery-plugin.version>
        <commons-validato.version>1.9.0</commons-validato.version>
        <commons-lang.version>2.6</commons-lang.version>
        <commons-lang3.version>3.17.0</commons-lang3.version>
        <jaxb-api.version>2.3.1</jaxb-api.version>
        <jaxb-impl.version>2.3.9</jaxb-impl.version>
        <jdom.version>1.1.3</jdom.version>
        <javax.mail.version>1.6.2</javax.mail.version>
        <jaxen.version>2.0.0</jaxen.version>
        <json-lib.version>2.4</json-lib.version>
        <slf4j-api.version>1.6.6</slf4j-api.version>
        <slf4j-log4j12.version>1.6.6</slf4j-log4j12.version>
        <javax.annotation-api.version>1.3.2</javax.annotation-api.version>
        <org.joda.time.version>1.6.2</org.joda.time.version>
        <netcdf.version>4.2</netcdf.version>
        <grib.version>8.0</grib.version>
        <unidataCommon.version>4.2.20</unidataCommon.version>
        <opendap.version>2.2.2</opendap.version>
        <!-- DEFINE your own war file name in the Production -->
        <war.name>eddy</war.name>
        <!-- DEFINE your own deployment directory in the Production -->
        <deploy.dir>/opt/devdata/ozflux/webapps</deploy.dir>

    </properties>
    <dependencies>
        <!-- Spring MVC Dependency -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aspects</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-oxm</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-instrument</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-instrument-tomcat</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-support</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <version>${spring.version}</version>
        </dependency>

        <!-- Spring ORM -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-orm</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.aopalliance</groupId>
            <artifactId>com.springsource.org.aopalliance</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>cglib</groupId>
            <artifactId>cglib</artifactId>
            <version>2.1_3</version>
        </dependency>

        <!-- Hibernate Core -->
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>${hibernate.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-envers</artifactId>
            <version>${hibernate.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hibernate.common</groupId>
            <artifactId>hibernate-commons-annotations</artifactId>
            <version>${hibernate-commons-annotations.version}</version>
        </dependency>

        <!-- Hibernate-C3P0 Integration -->
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-c3p0</artifactId>
            <version>${hibernate.version}</version>
        </dependency>

        <!-- c3p0 -->
        <dependency>
            <groupId>com.mchange</groupId>
            <artifactId>c3p0</artifactId>
            <version>${c3p0.version}</version>
        </dependency>

        <!-- Hibernate Validator -->
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>${hibernate.validator.version}</version>
        </dependency>

        <!-- Servlet Dependency -->
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>${servlets.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>${postgresql.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.reload4j</groupId>
            <artifactId>reload4j</artifactId>
            <version>${reload4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.struts</groupId>
            <artifactId>struts2-core</artifactId>
            <version>${struts2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.struts</groupId>
            <artifactId>struts2-spring-plugin</artifactId>
            <version>${struts2.version}</version>
        </dependency>
        <dependency>
            <groupId>com.jgeppert.struts2.jquery</groupId>
            <artifactId>struts2-jquery-plugin</artifactId>
            <version>${struts2-jquery-plugin.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.struts</groupId>
            <artifactId>struts2-json-plugin</artifactId>
            <version>${struts2.version}</version>
        </dependency>

        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>${freemarker.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
            <version>${commons-validato.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>${commons-lang.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang3.version}</version>
        </dependency>

        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>${jaxb-api.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>${jaxb-impl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jdom</groupId>
            <artifactId>jdom</artifactId>
            <version>${jdom.version}</version>
        </dependency>

        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>${javax.mail.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.activation</groupId>
                    <artifactId>activation</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.sf.json-lib</groupId>
            <artifactId>json-lib</artifactId>
            <version>${json-lib.version}</version>
        </dependency>
        <dependency>
            <groupId>jaxen</groupId>
            <artifactId>jaxen</artifactId>
            <version>${jaxen.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j-api.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${slf4j-log4j12.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>${javax.annotation-api.version}</version>
        </dependency>

        <dependency>
            <groupId>org.joda</groupId>
            <artifactId>com.springsource.org.joda.time</artifactId>
            <version>${org.joda.time.version}</version>
        </dependency>

        <!-- NETCDF libs -->
        <dependency>
            <groupId>edu.ucar</groupId>
            <artifactId>unidataCommon</artifactId>
            <version>${unidataCommon.version}</version>
        </dependency>

        <dependency>
            <groupId>edu.ucar</groupId>
            <artifactId>grib</artifactId>
            <version>${grib.version}</version>
        </dependency>

        <dependency>
            <groupId>edu.ucar</groupId>
            <artifactId>netcdf</artifactId>
            <version>${netcdf.version}</version>
        </dependency>

        <!-- uk.ca libs  maybe it's useful -->
        <dependency>
            <groupId>uk.ac.rdg.resc</groupId>
            <artifactId>edal-common</artifactId>
            <version>1.5.3</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>uk.ac.rdg.resc</groupId>
            <artifactId>edal-cdm</artifactId>
            <version>1.5.3</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>uk.ac.rdg.resc</groupId>
            <artifactId>edal-graphics</artifactId>
            <version>1.5.3</version>
            <scope>provided</scope>
        </dependency>
        <!-- End of uk.ca libs  maybe it's useful -->

        <dependency>
            <groupId>edu.ucar</groupId>
            <artifactId>opendap</artifactId>
            <version>${opendap.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>servlet-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jdom</groupId>
                    <artifactId>jdom</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!--        <dependency>-->
        <!--            <groupId>edu.wisc</groupId>-->
        <!--            <artifactId>visadnodods</artifactId>-->
        <!--            <version>2011.08.22</version>-->
        <!--        </dependency>-->
    </dependencies>

    <build>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <directory>etc</directory>
            </resource>
        </resources>
        <finalName>${war.name}-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.4.0</version>
                <!-- remove the deployed war and unpack war directory if any-->
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>${deploy.dir}</directory>
                            <includes>
                                <include>*.war</include>
                            </includes>
                        </fileset>
                        <fileset>
                            <directory>${deploy.dir}/${war.name}</directory>
                            <includes>
                                <include>**</include>
                            </includes>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.3.2</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-install-plugin</artifactId>-->
<!--                <version>3.1.3</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <configuration>-->
<!--                            <file>${pom.basedir}/lib/net-cdf-lib/netcdf-4.2.jar</file>-->
<!--                            <generatePom>true</generatePom>-->
<!--                            <groupId>edu.ucar</groupId>-->
<!--                            <artifactId>netcdf</artifactId>-->
<!--                            <version>4.2</version>-->
<!--                            <packaging>jar</packaging>-->
<!--                        </configuration>-->
<!--                        <id>install-netcdf</id>-->
<!--                        <goals>-->
<!--                            <goal>install-file</goal>-->
<!--                        </goals>-->
<!--                        <phase>validate</phase>-->
<!--                    </execution>-->
<!--                    <execution>-->
<!--                        <configuration>-->
<!--                            <file>${pom.basedir}/lib/net-cdf-lib/visadnodods-2011.08.22.jar</file>-->
<!--                            <generatePom>true</generatePom>-->
<!--                            <groupId>edu.wisc</groupId>-->
<!--                            <artifactId>visadnodods</artifactId>-->
<!--                            <version>2011.08.22</version>-->
<!--                            <packaging>jar</packaging>-->
<!--                        </configuration>-->
<!--                        <id>install-visad</id>-->
<!--                        <goals>-->
<!--                            <goal>install-file</goal>-->
<!--                        </goals>-->
<!--                        <phase>validate</phase>-->
<!--                    </execution>-->
<!--                    <execution>-->
<!--                        <configuration>-->
<!--                            <file>${pom.basedir}/lib/net-cdf-lib/grib-8.0.jar</file>-->
<!--                            <generatePom>true</generatePom>-->
<!--                            <groupId>edu.ucar</groupId>-->
<!--                            <artifactId>grib</artifactId>-->
<!--                            <version>${grib.version}</version>-->
<!--                            <packaging>jar</packaging>-->
<!--                        </configuration>-->
<!--                        <id>install-grib</id>-->
<!--                        <goals>-->
<!--                            <goal>install-file</goal>-->
<!--                        </goals>-->
<!--                        <phase>validate</phase>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
            <plugin>
                <groupId>com.coderplus.maven.plugins</groupId>
                <artifactId>copy-rename-maven-plugin</artifactId>
                <version>1.0</version>
                <executions>
                    <execution>
                        <id>copy-file</id>
                        <phase>install</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <sourceFile>target/${war.name}-${project.version}.war</sourceFile>
                            <destinationFile>${deploy.dir}/${war.name}.war</destinationFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>project-local-libs</id>
            <url>file://${project.basedir}/lib</url>
        </repository>

        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>java.net</id>
            <name>Java Net Maven Repository</name>
            <url>https://download.java.net/maven/2/</url>
        </repository>
        <repository>
            <id>public</id>
            <name>Nexeo Public</name>
            <url>https://maven.nuxeo.org/nexus/content/groups/public</url>
        </repository>
    </repositories>
</project>
