############## Application Configuration######################
#    This file should be replaced by configuration values
#    during the installation process
##############################################################
############## App Basic Info  ###############################
application.name=Ecosystem
data.capture.adapter.class=au.edu.monash.merc.capture.adapter.NetCDFDataCaptureAdapter
data.store.location=/opt/datastore/ands
#TERN Data Licence
tern.data.licence=http://www.tern.org.au/datalicence/TERN-BY-SA-NC/1.0
#Physical address of the collections
data.collections.physical.location=Monash University Clayton Campus Building 26 Clayton 3800 Victoria
#Collection uuid prefix
data.collection.uuid.prefix=MON
#Search dataset level enable
data.search.dataset.level.enable=true
############### Administrator Section ########################
#Primary super administrator name and password and email
admin.user.email=xiaoming.yu@monash.edu
#Admin display name
admin.user.displayName=Simon Yu
#Admin password
admin.user.password=admin_password
#System service email for sending and receiving emails which may be different for admin emai
system.service.email=xm.yuau@gmail.com
##############     Security  #################################
#How many trying times does the system allow?
allow.login.try.times=8
#Block ip waiting time in minutes after n trying times failed
login.ip.block.waiting.time=15
# Security Hash. You should change this value just before the first run of your forum.
#The value can be anything and should very a large and complex sequence.
#This value will be used to increase security, and This value will be a MD5 hash value
user.security.hash.sequence=2fac07501937914eed66c098a29ff345
#Group name in the rifcs and citation info
ands.rifcs.register.group.name=OzFlux: Australian and New Zealand Flux Research and Monitoring
# Published RIF-CS File Store Location
ands.rifcs.files.store.location=/opt/datastore/rifcs
# set google map enable or not
google.map.enabled=true
